# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        language: node
        entry: prettier
        args: [--write, --ignore-unknown]
        types: [file]
        additional_dependencies:
          - prettier@3.6.2

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: b84c4a0a90bd58c7d82ae8f0d4d5e77b1ddd3ce6 # frozen: 0.12.5
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: aab412d509121cb5f7533134b7e67f9fab59c682 # frozen: v0.16.4
    hooks:
      - id: ruff-check
        types_or: [python, pyi, jupyter, pyproject]
        args: [--fix, --show-fixes]
      - id: ruff-format

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: e0bc482078af7eee1555b1f01d27e618d2212720 # frozen: v0.0.73
    hooks:
      - id: ty
        args:
          - --isolated
          - --locked
